### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by peoray** [DavidCouronne/gridsome-plugin-remark-prismjs-all#1]
The demo page doesn't work and only shows a not found message on the browser

**Comment by DavidCouronne** [comment]
https://5e145900f69efacdc2a95dfe--kind-elion-23889d.netlify.com/demo-gridsome-plugin-remark-prismjs-all/

Fixed

**Comment by peoray** [comment]
What theme are you using for the article. I prefer a black theme for code but it seems none of the default themes is dark

**Comment by DavidCouronne** [comment]
I use tomorrow theme.
In `main.js`:
```javascript
require('prismjs/themes/prism-tomorrow.css');
```

**Comment by peoray** [comment]
Well, somehow it doesn't render the way it does in yours, perhap, there are conflicting styles. it's not important though

**Comment by DavidCouronne** [comment]
Hello,

I've made an update for the plugin, and add two built-in theme: tomorrow-night and night-owl.

Update to version 0.2.6 and in `main.js` just add:

```js
// In your main.js
require('gridsome-plugin-remark-prismjs-all/themes/tomorrow.css');
```

or

```js
// In your main.js
require('gridsome-plugin-remark-prismjs-all/themes/night-owl.css');
```

Happy Coding !

**Comment by peoray** [comment]
This is great. Definitely gonna be switching to night-owl. Thanks for the work you put in :)

**Comment by peoray** [comment]
Hey. Sorry if this is a dumb question. How do I use this in an existing project as mine? I mean the new theme. I want to use the night owl. I believe it's the one by Sarah Drasner?
